version: "3"

services:
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/backend
      - public:/backend/public
      - tmp:/backend/tmp
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/data/:/var/lib/mysql

  nginx:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/backend/public
      - tmp:/backend/tmp
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  tmp:
  public:
